// 美文π 主题系统
// 每个主题是一组「标签 -> 内联样式」的 token 配置。
// 关键点：公众号会剥离 class 与外链 CSS，所以预览与复制都使用内联样式，
// 保证「复制粘贴到公众号零错乱」。
//
// 风格体系参照主流公众号编辑器（如 135 编辑器）的公开分类维度，
// 但所有 CSS 均为原创编写，不引用任何第三方版权素材。

export type StyleMap = Record<string, string>

export interface Theme {
  id: string
  name: string
  description: string
  /** 预览画布外层底色（桌面背景） */
  pageBg: string
  /** 文章容器 <section> 的样式 */
  container: StyleMap
  h1: StyleMap
  h2: StyleMap
  h3: StyleMap
  p: StyleMap
  strong: StyleMap
  em: StyleMap
  a: StyleMap
  blockquote: StyleMap
  code: StyleMap // 行内代码
  pre: StyleMap // 代码块容器
  preCode: StyleMap // 代码块内文本
  ul: StyleMap
  ol: StyleMap
  li: StyleMap
  hr: StyleMap
  img: StyleMap
  mark: StyleMap // ==高亮文本==
  small: StyleMap // 行内小字标注（图片注释、次要说明）
}

const SERIF =
  '"Noto Serif SC", "Songti SC", "STSong", "SimSun", serif'
const SANS =
  '"PingFang SC", "Microsoft YaHei", "Hiragino Sans GB", "Helvetica Neue", sans-serif'
const MONO =
  '"SFMono-Regular", "Menlo", "Consolas", "Liberation Mono", monospace'

// 基础中性主题：各风格在其上做差异化覆盖，减少重复代码
const BASE: Omit<Theme, 'id' | 'name' | 'description' | 'pageBg'> = {
  container: {
    background: '#ffffff',
    padding: '28px 22px',
    'font-family': SANS,
    color: '#333333',
    'font-size': '16px',
    'line-height': '1.9',
  },
  h1: {
    'font-size': '22px',
    'font-weight': '700',
    color: '#222222',
    'margin': '28px 0 16px',
    'letter-spacing': '0.5px',
  },
  h2: {
    'font-size': '19px',
    'font-weight': '700',
    color: '#222222',
    'margin': '22px 0 12px',
    'border-left': '4px solid #dddddd',
    'padding-left': '10px',
  },
  h3: {
    'font-size': '16px',
    'font-weight': '600',
    color: '#444444',
    'margin': '16px 0 10px',
  },
  p: { 'margin': '14px 0', color: '#444444', 'line-height': '1.9' },
  strong: { 'font-weight': '700', color: '#222222' },
  em: { 'font-style': 'italic', color: '#666666' },
  a: {
    color: '#2563eb',
    'text-decoration': 'none',
    'border-bottom': '1px solid #2563eb',
  },
  blockquote: {
    background: '#f7f7f7',
    'border-left': '3px solid #dddddd',
    padding: '10px 16px',
    margin: '16px 0',
    color: '#666666',
  },
  code: {
    background: '#f0f0f0',
    color: '#d63384',
    padding: '2px 5px',
    'border-radius': '4px',
    'font-family': MONO,
    'font-size': '14px',
  },
  pre: {
    background: '#1e1e1e',
    padding: '16px',
    'border-radius': '6px',
    margin: '16px 0',
    overflow: 'auto',
    color: '#e6e6e6',
  },
  preCode: {
    color: '#e6e6e6',
    'font-family': MONO,
    'font-size': '14px',
    background: 'transparent',
    padding: '0',
  },
  ul: { 'margin': '14px 0', 'padding-left': '24px' },
  ol: { 'margin': '14px 0', 'padding-left': '24px' },
  li: { 'margin': '7px 0', 'line-height': '1.8' },
  hr: { border: 'none', 'border-top': '1px solid #eaeaea', margin: '24px 0' },
  img: {
    'max-width': '100%',
    'border-radius': '6px',
    display: 'block',
    margin: '16px auto',
  },
  mark: {
    background: '#fff3b0',
    color: '#333333',
    padding: '2px 4px',
    'border-radius': '3px',
  },
  small: { color: '#999999', 'font-size': '12px' },
}

type ThemeSeed = {
  id: string
  name: string
  description: string
  pageBg: string
} & Partial<Omit<Theme, 'id' | 'name' | 'description' | 'pageBg'>>

function theme(seed: ThemeSeed): Theme {
  return { ...BASE, ...seed } as Theme
}

export const themes: Theme[] = [
  theme({
    id: 'literary',
    name: '文艺',
    description: '衬线字体 · 米白底 · 墨绿赭石点缀，清新高级',
    pageBg: '#f5f1e8',
    container: {
      background: '#fffdf8',
      padding: '26px 22px',
      'font-family': SERIF,
      color: '#3a3a3a',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.4px',
    },
    h1: {
      'font-size': '22px',
      'font-weight': '700',
      color: '#2f4f3e',
      'text-align': 'center',
      'margin': '30px 0 18px',
      'letter-spacing': '3px',
      'border-bottom': '1px solid #e8e0d0',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '20px',
      'font-weight': '700',
      color: '#2f4f3e',
      'margin': '26px 0 12px',
      'border-left': '4px solid #c9a86a',
      'padding-left': '12px',
    },
    h3: { 'font-size': '17px', 'font-weight': '600', color: '#5a5a4a' },
    p: { 'margin': '14px 0', 'line-height': '1.95', color: '#444444' },
    strong: { color: '#a0522d', 'font-weight': '700' },
    em: { color: '#7a6a4f', 'font-style': 'italic' },
    a: {
      color: '#2f7d6b',
      'text-decoration': 'none',
      'border-bottom': '1px solid #2f7d6b',
    },
    blockquote: {
      background: '#f3efe4',
      'border-left': '4px solid #c9a86a',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b6256',
      'font-style': 'italic',
      'border-radius': '0 8px 8px 0',
    },
    mark: { background: '#fff3b0', color: '#333333' },
  }),
  theme({
    id: 'minimal',
    name: '简约',
    description: '无衬线 · 黑白灰 · 干净利落',
    pageBg: '#fafafa',
    container: {
      background: '#ffffff',
      padding: '30px 24px',
      'font-family': SANS,
      color: '#222222',
      'font-size': '16px',
      'line-height': '1.85',
    },
    h1: {
      'font-size': '22px',
      'font-weight': '800',
      color: '#111111',
      'margin': '30px 0 16px',
      'letter-spacing': '0',
    },
    h2: {
      'font-size': '20px',
      'font-weight': '700',
      color: '#111111',
      'margin': '24px 0 12px',
      'border-bottom': '2px solid #111111',
      'padding-bottom': '6px',
      'display': 'inline-block',
    },
    h3: { 'font-size': '17px', 'font-weight': '600' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.85' },
    strong: { 'font-weight': '700', color: '#222222' },
    em: { 'font-style': 'italic', color: '#555555' },
    a: { color: '#0066cc', 'text-decoration': 'underline' },
    blockquote: {
      'border-left': '3px solid #dddddd',
      padding: '8px 16px',
      margin: '16px 0',
      color: '#666666',
      background: '#f7f7f7',
    },
    mark: { background: '#ffe066', color: '#222222' },
  }),
  theme({
    id: 'business',
    name: '商务',
    description: '深蓝灰 · 规整专业，适合职场内容',
    pageBg: '#eef1f5',
    container: {
      background: '#ffffff',
      padding: '32px 28px',
      'font-family': SANS,
      color: '#2c3e50',
      'font-size': '15px',
      'line-height': '1.88',
    },
    h1: {
      'font-size': '22px',
      'font-weight': '700',
      color: '#1a365d',
      'text-align': 'center',
      'margin': '28px 0 18px',
      'border-bottom': '2px solid #1a365d',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#1a365d',
      'margin': '22px 0 12px',
      'border-left': '4px solid #2b6cb0',
      'padding-left': '10px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#2d3748' },
    p: { 'margin': '13px 0', color: '#374151', 'line-height': '1.88' },
    strong: { color: '#1a365d', 'font-weight': '700' },
    em: { color: '#4a5568', 'font-style': 'italic' },
    a: {
      color: '#2b6cb0',
      'text-decoration': 'none',
      'border-bottom': '1px solid #2b6cb0',
    },
    blockquote: {
      background: '#f0f4f8',
      'border-left': '4px solid #2b6cb0',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#4a5568',
      'border-radius': '4px',
    },
    mark: { background: '#fefcbf', color: '#744210' },
  }),
  theme({
    id: 'fresh',
    name: '清新',
    description: '薄荷绿 · 圆角留白 · 清爽通透',
    pageBg: '#eef7f0',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#374151',
      'font-size': '16px',
      'line-height': '1.9',
      'border-radius': '16px',
    },
    h1: {
      'font-size': '22px',
      'font-weight': '700',
      color: '#1f7a4d',
      'text-align': 'center',
      'margin': '26px 0 16px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#1f7a4d',
      'margin': '22px 0 12px',
      'border-left': '4px solid #5fd39a',
      'padding-left': '10px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#2f855a' },
    p: { 'margin': '14px 0', color: '#3f3f46' },
    strong: { color: '#1f7a4d', 'font-weight': '700' },
    em: { color: '#5a8a6f', 'font-style': 'italic' },
    a: {
      color: '#1f7a4d',
      'text-decoration': 'none',
      'border-bottom': '1px solid #1f7a4d',
    },
    blockquote: {
      background: '#f0faf4',
      'border-left': '4px solid #5fd39a',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#4b7c63',
      'border-radius': '0 10px 10px 0',
    },
    mark: { background: '#d8f5e3', color: '#1f7a4d' },
  }),
  theme({
    id: 'cartoon',
    name: '卡通',
    description: '亮橙明黄 · 圆润活泼 · 童趣亲和',
    pageBg: '#fff7ed',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#4a3f35',
      'font-size': '16px',
      'line-height': '1.85',
      'border-radius': '18px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '800',
      color: '#ea580c',
      'text-align': 'center',
      'margin': '24px 0 16px',
      'text-shadow': '0 2px 0 #ffe1c2',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#ea580c',
      'margin': '20px 0 12px',
      'background': '#fff1e0',
      'padding': '8px 12px',
      'border-radius': '10px',
    },
    h3: { 'font-size': '16px', 'font-weight': '700', color: '#c2410c' },
    p: { 'margin': '13px 0', color: '#5b4a3a' },
    strong: { color: '#ea580c', 'font-weight': '800' },
    em: { color: '#b45309', 'font-style': 'italic' },
    a: {
      color: '#ea580c',
      'text-decoration': 'none',
      'border-bottom': '2px dashed #fdba74',
    },
    blockquote: {
      background: '#fff7ed',
      'border-left': '5px solid #fb923c',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#9a6b3f',
      'border-radius': '0 12px 12px 0',
    },
    mark: { background: '#fde68a', color: '#7c4a03' },
  }),
  theme({
    id: 'fashion',
    name: '时尚',
    description: '黑白金 · 大字留白 · 摩登高冷',
    pageBg: '#1c1c1c',
    container: {
      background: '#faf7f2',
      padding: '34px 28px',
      'font-family': SANS,
      color: '#1a1a1a',
      'font-size': '15px',
      'line-height': '1.95',
    },
    h1: {
      'font-size': '26px',
      'font-weight': '800',
      color: '#111111',
      'text-align': 'center',
      'margin': '30px 0 18px',
      'letter-spacing': '4px',
      'text-transform': 'uppercase',
    },
    h2: {
      'font-size': '20px',
      'font-weight': '700',
      color: '#111111',
      'margin': '24px 0 12px',
      'border-left': '4px solid #c9a227',
      'padding-left': '12px',
      'letter-spacing': '1px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#333333' },
    p: { 'margin': '14px 0', color: '#2b2b2b' },
    strong: { color: '#c9a227', 'font-weight': '700' },
    em: { color: '#555555', 'font-style': 'italic' },
    a: {
      color: '#c9a227',
      'text-decoration': 'none',
      'border-bottom': '1px solid #c9a227',
    },
    blockquote: {
      background: '#f1ece2',
      'border-left': '4px solid #c9a227',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#5a5346',
      'border-radius': '0 8px 8px 0',
    },
    mark: { background: '#f4e3b0', color: '#5a4a12' },
  }),
  theme({
    id: 'dynamic',
    name: '动态',
    description: '渐变紫蓝 · 光影流动 · 年轻吸睛',
    pageBg: '#0f1226',
    container: {
      background: '#ffffff',
      padding: '30px 24px',
      'font-family': SANS,
      color: '#2d2a4a',
      'font-size': '16px',
      'line-height': '1.9',
      'border-radius': '18px',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '800',
      color: '#6d28d9',
      'text-align': 'center',
      'margin': '28px 0 16px',
      'background':
        'linear-gradient(90deg, #7c3aed, #2563eb)',
      '-webkit-background-clip': 'text',
      '-webkit-text-fill-color': 'transparent',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#6d28d9',
      'margin': '22px 0 12px',
      'border-left': '4px solid #8b5cf6',
      'padding-left': '10px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#7c3aed' },
    p: { 'margin': '14px 0', color: '#3b3656' },
    strong: { color: '#6d28d9', 'font-weight': '700' },
    em: { color: '#7c3aed', 'font-style': 'italic' },
    a: {
      color: '#6d28d9',
      'text-decoration': 'none',
      'border-bottom': '1px solid #8b5cf6',
    },
    blockquote: {
      background: '#f5f3ff',
      'border-left': '4px solid #8b5cf6',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b5ca5',
      'border-radius': '0 12px 12px 0',
    },
    mark: { background: '#ede9fe', color: '#5b21b6' },
  }),
  theme({
    id: 'china',
    name: '中国风',
    description: '朱红描金 · 宋体典雅 · 东方韵味',
    pageBg: '#f3e9e0',
    container: {
      background: '#fbf6ef',
      padding: '30px 24px',
      'font-family': SERIF,
      color: '#3b2f2a',
      'font-size': '16px',
      'line-height': '1.95',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#b91c1c',
      'text-align': 'center',
      'margin': '28px 0 18px',
      'letter-spacing': '4px',
      'border-bottom': '1px solid #e7c9a9',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#b91c1c',
      'margin': '22px 0 12px',
      'border-left': '4px solid #c9a227',
      'padding-left': '12px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#9a3412' },
    p: { 'margin': '14px 0', color: '#4a3b33' },
    strong: { color: '#b91c1c', 'font-weight': '700' },
    em: { color: '#9a3412', 'font-style': 'italic' },
    a: {
      color: '#b91c1c',
      'text-decoration': 'none',
      'border-bottom': '1px solid #c9a227',
    },
    blockquote: {
      background: '#f7efe4',
      'border-left': '4px solid #c9a227',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#7a5c3a',
      'border-radius': '0 8px 8px 0',
    },
    mark: { background: '#fde9c8', color: '#7c4a12' },
  }),
  theme({
    id: 'clean',
    name: '极简',
    description: '纯白 ample · 细线大字 · 极致留白',
    pageBg: '#ffffff',
    container: {
      background: '#ffffff',
      padding: '40px 30px',
      'font-family': SANS,
      color: '#1f1f1f',
      'font-size': '16px',
      'line-height': '2',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '300',
      color: '#111111',
      'text-align': 'center',
      'margin': '34px 0 20px',
      'letter-spacing': '2px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '400',
      color: '#111111',
      'margin': '26px 0 14px',
      'border-left': '2px solid #111111',
      'padding-left': '12px',
    },
    h3: { 'font-size': '16px', 'font-weight': '400', color: '#333333' },
    p: { 'margin': '16px 0', color: '#2b2b2b' },
    strong: { 'font-weight': '600', color: '#111111' },
    em: { color: '#666666', 'font-style': 'italic' },
    a: { color: '#111111', 'text-decoration': 'underline' },
    blockquote: {
      background: 'transparent',
      'border-left': '2px solid #111111',
      padding: '8px 16px',
      margin: '18px 0',
      color: '#555555',
    },
    mark: { background: '#f0f0f0', color: '#111111' },
  }),
  theme({
    id: 'ins',
    name: 'ins风',
    description: '莫兰迪奶油 · 柔和低饱和 · 氛围质感',
    pageBg: '#efe9e3',
    container: {
      background: '#fbf8f4',
      padding: '30px 24px',
      'font-family': SANS,
      color: '#5b534c',
      'font-size': '16px',
      'line-height': '1.9',
      'border-radius': '14px',
    },
    h1: {
      'font-size': '22px',
      'font-weight': '600',
      color: '#8a7a6a',
      'text-align': 'center',
      'margin': '28px 0 16px',
      'letter-spacing': '2px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '600',
      color: '#8a7a6a',
      'margin': '22px 0 12px',
      'border-left': '4px solid #d8c7b6',
      'padding-left': '10px',
    },
    h3: { 'font-size': '16px', 'font-weight': '500', color: '#9a8c7c' },
    p: { 'margin': '14px 0', color: '#6b6259' },
    strong: { color: '#8a7a6a', 'font-weight': '700' },
    em: { color: '#a89484', 'font-style': 'italic' },
    a: {
      color: '#a07e5e',
      'text-decoration': 'none',
      'border-bottom': '1px solid #d8c7b6',
    },
    blockquote: {
      background: '#f3ede6',
      'border-left': '4px solid #d8c7b6',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#8a7c6c',
      'border-radius': '0 10px 10px 0',
    },
    mark: { background: '#ece2d6', color: '#6b5a45' },
  }),
  theme({
    id: 'solar',
    name: '节气',
    description: '秋香黄绿 · 米白暖底 · 适合节气/节日长图文',
    pageBg: '#f6f4eb',
    container: {
      background: '#fffefb',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#4a453a',
      'font-size': '16px',
      'line-height': '1.95',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#5c6b2e',
      'text-align': 'center',
      'margin': '26px 0 18px',
      'letter-spacing': '2px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#5c6b2e',
      'margin': '24px 0 14px',
      'padding': '8px 14px',
      'background': '#f3f6e6',
      'border-radius': '10px',
      'border-left': '5px solid #a3b33a',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#7a8745' },
    p: { 'margin': '14px 0', color: '#4a453a', 'line-height': '1.95' },
    strong: { color: '#7a8745', 'font-weight': '700' },
    em: { color: '#8a825a', 'font-style': 'italic' },
    a: {
      color: '#7a8745',
      'text-decoration': 'none',
      'border-bottom': '1px solid #a3b33a',
    },
    blockquote: {
      background: '#f7f6ef',
      'border-left': '4px solid #a3b33a',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b6548',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #d5d9c4', margin: '24px 0' },
    mark: { background: '#eef2d6', color: '#5c6b2e' },
  }),
  theme({
    id: 'solar-summer',
    name: '盛夏',
    description: '粉荷配色 · 清新夏日 · 适合小暑/夏至/荷花主题',
    pageBg: '#fff5f7',
    container: {
      background: '#fffafa',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#5a4a4a',
      'font-size': '16px',
      'line-height': '1.95',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#4a7c59',
      'text-align': 'center',
      'margin': '26px 0 10px',
      'letter-spacing': '2px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#4a7c59',
      'margin': '24px 0 14px',
      'padding': '8px 14px',
      'background': '#fff0f3',
      'border-radius': '10px',
      'border-left': '5px solid #f4a4b4',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#7a9a7a' },
    p: { 'margin': '14px 0', color: '#5a4a4a', 'line-height': '1.95' },
    strong: { color: '#4a7c59', 'font-weight': '700' },
    em: { color: '#a08080', 'font-style': 'italic' },
    a: {
      color: '#4a7c59',
      'text-decoration': 'none',
      'border-bottom': '1px solid #f4a4b4',
    },
    blockquote: {
      background: '#fff5f7',
      'border-left': '4px solid #f4a4b4',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#7a6a6a',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #f4d4dc', margin: '24px 0' },
    mark: { background: '#ffeaf0', color: '#6b4a52' },
  }),
  theme({
    id: 'summer-cool',
    name: '清凉',
    description: '天蓝冰爽 · 夏日公益 · 适合送清凉/慰问活动',
    pageBg: '#f0f9ff',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#334155',
      'font-size': '16px',
      'line-height': '1.95',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#0c4a6e',
      'text-align': 'center',
      'margin': '26px 0 16px',
      'letter-spacing': '1px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#075985',
      'margin': '24px 0 14px',
      'padding': '8px 14px',
      'background': '#e0f2fe',
      'border-radius': '10px',
      'border-left': '5px solid #38bdf8',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#0369a1' },
    p: { 'margin': '14px 0', color: '#334155', 'line-height': '1.95' },
    strong: { color: '#0284c7', 'font-weight': '700' },
    em: { color: '#0ea5e9', 'font-style': 'italic' },
    a: {
      color: '#0284c7',
      'text-decoration': 'none',
      'border-bottom': '1px solid #7dd3fc',
    },
    blockquote: {
      background: '#f0f9ff',
      'border-left': '4px solid #38bdf8',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#0c4a6e',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #bae6fd', margin: '24px 0' },
    mark: { background: '#e0f2fe', color: '#075985' },
  }),
  theme({
    id: 'spring',
    name: '春日',
    description: '藕荷淡紫 · 薄荷点缀 · 文艺清新，适合散文/随笔/节气',
    pageBg: '#f3f0f8',
    container: {
      background: '#fffdfe',
      padding: '28px 22px',
      'font-family': SERIF,
      color: '#4a4458',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#7c6fb0',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '3px',
      'border-bottom': '1px solid #e4def2',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#7c6fb0',
      'text-align': 'center',
      'margin': '26px auto 14px',
      'letter-spacing': '2px',
      'border-top': '1px solid #e4def2',
      'border-bottom': '1px solid #e4def2',
      'padding': '10px 0',
      'max-width': '85%',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#8b7cc0' },
    p: { 'margin': '14px 0', color: '#4a4458', 'line-height': '1.95' },
    strong: { color: '#6f5fa6', 'font-weight': '700' },
    em: { color: '#8a7aa8', 'font-style': 'italic' },
    a: {
      color: '#8b7cc0',
      'text-decoration': 'none',
      'border-bottom': '1px solid #c9bce8',
    },
    blockquote: {
      background: '#f7f4fc',
      'border-left': '4px solid #aca2ce',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b5f8a',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #e0d8f0', margin: '24px 0' },
    mark: { background: '#efeafc', color: '#5b4a8f' },
  }),
  // 天凉好个秋：清凉蓝 · 渐变标题条（复刻 135「天凉好个秋一键排版」）
  theme({
    id: 'autumn',
    name: '天凉好个秋',
    description: '清凉蓝 · 渐变标题条 · 秋日文艺，适合散文/随笔/节气',
    pageBg: '#eef7f7',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#333333',
      'font-size': '16px',
      'line-height': '1.9',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#036eb8',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '1px solid #cfe6f2',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '17px',
      'font-weight': '700',
      color: '#036eb8',
      'text-align': 'center',
      'margin': '24px auto 14px',
      'letter-spacing': '1px',
      'background': 'linear-gradient(to right, #ace1f3, #edf7f7)',
      'border-radius': '6px',
      'padding': '8px 10px',
      'max-width': '92%',
    },
    h3: { 'font-size': '15px', 'font-weight': '600', color: '#2e5e93' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.9' },
    strong: { color: '#036eb8', 'font-weight': '700' },
    em: { color: '#2e5e93', 'font-style': 'italic' },
    a: {
      color: '#036eb8',
      'text-decoration': 'none',
      'border-bottom': '1px solid #a9d4ea',
    },
    blockquote: {
      background: '#eef7f7',
      'border-left': '4px solid #036eb8',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#3a5a78',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #b9dcec', margin: '24px 0' },
    mark: { background: '#d6f0f9', color: '#036eb8' },
  }),
  // 开学：暖黄米色 · 校园开学（复刻 135「开学通知一键排版」）
  theme({
    id: 'campus',
    name: '开学',
    description: '暖黄米色 · 校园开学 · 适合开学通知/校园活动',
    pageBg: '#faf3e8',
    container: {
      background: '#fffbf5',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#333333',
      'font-size': '16px',
      'line-height': '1.95',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#d98f2a',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #fec55c',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#d98f2a',
      'margin': '24px 0 14px',
      'padding': '9px 16px',
      'background': '#faf3e8',
      'border-left': '5px solid #fec55c',
      'border-radius': '8px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#c97f22' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.95' },
    strong: { color: '#d98f2a', 'font-weight': '700' },
    em: { color: '#5fa37e', 'font-style': 'italic' },
    a: { color: '#d98f2a', 'text-decoration': 'none', 'border-bottom': '1px solid #fec55c' },
    blockquote: {
      background: '#faf3e8',
      'border-left': '4px solid #5fa37e',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b6256',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #f0d9a8', margin: '24px 0' },
    mark: { background: '#fec55c', color: '#5a3d00' },
  }),
  // 文艺清新：淡蓝描边 · 灰调文艺（复刻 135「文艺清新一键排版」）
  theme({
    id: 'freshblue',
    name: '文艺清新',
    description: '淡蓝描边 · 灰调文艺 · 适合散文/随笔/读书',
    pageBg: '#eef6fd',
    container: {
      background: '#ffffff',
      padding: '30px 24px',
      'font-family': SERIF,
      color: '#595959',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#59aae8',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '3px',
      'border-bottom': '1px solid #d4ebff',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#59aae8',
      'margin': '24px 0 14px',
      'border-left': '4px solid #d4ebff',
      'padding-left': '12px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#7bb8e8' },
    p: { 'margin': '14px 0', color: '#595959', 'line-height': '1.95' },
    strong: { color: '#59aae8', 'font-weight': '700' },
    em: { color: '#7bb8e8', 'font-style': 'italic' },
    a: { color: '#59aae8', 'text-decoration': 'none', 'border-bottom': '1px solid #d4ebff' },
    blockquote: {
      background: '#f5faff',
      'border-left': '4px solid #d4ebff',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b8aa8',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #d4ebff', margin: '24px 0' },
    mark: { background: '#d4ebff', color: '#2c6aa0' },
  }),
  // 寒假旅行：天蓝浅底 · 暖黄点缀（复刻 135「寒假旅行一键排版」）
  theme({
    id: 'winter',
    name: '寒假旅行',
    description: '天蓝浅底 · 暖黄点缀 · 适合旅行/冬日/节日',
    pageBg: '#eef4fc',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#222222',
      'font-size': '16px',
      'line-height': '1.95',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#2f7fd0',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '2px solid #80baf8',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#ffffff',
      'margin': '22px 0 14px',
      'padding': '9px 16px',
      'background': '#80baf8',
      'border-radius': '7px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#5a9be0' },
    p: { 'margin': '14px 0', color: '#222222', 'line-height': '1.95' },
    strong: { color: '#2f7fd0', 'font-weight': '700' },
    em: { color: '#c79a3a', 'font-style': 'italic' },
    a: { color: '#2f7fd0', 'text-decoration': 'none', 'border-bottom': '1px solid #80baf8' },
    blockquote: {
      background: '#f6faff',
      'border-left': '4px solid #80baf8',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#3a5a78',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #b9d4f0', margin: '24px 0' },
    mark: { background: '#ffd88f', color: '#5a3d00' },
  }),
  // 旅行感悟：暖橙 + 天蓝双色 · 文艺旅途（复刻 135「旅行感悟一键排版」）
  theme({
    id: 'travel',
    name: '旅行感悟',
    description: '暖橙天蓝 · 双色点缀 · 文艺旅途，适合旅行/随笔/生活方式',
    pageBg: '#f2f6fd',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SERIF,
      color: '#333333',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#5f7ad2',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #ffb373',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#5f7ad2',
      'margin': '24px 0 14px',
      'padding': '9px 16px',
      'background': '#eaf4ff',
      'border-left': '5px solid #b1cff3',
      'border-radius': '8px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#6f8fd0' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.95' },
    strong: { color: '#5f7ad2', 'font-weight': '700' },
    em: { color: '#c98a4a', 'font-style': 'italic' },
    a: { color: '#5f7ad2', 'text-decoration': 'none', 'border-bottom': '1px solid #b1cff3' },
    blockquote: {
      background: '#fff4ec',
      'border-left': '4px solid #ffb373',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b5a4a',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #ffd5b2', margin: '24px 0' },
    mark: { background: '#ffd5b2', color: '#5a3d00' },
  }),
  // 咖啡店：暖黄 + 蓝灰 · 文艺小清新（复刻 135「咖啡店介绍一键排版」）
  theme({
    id: 'cafe',
    name: '咖啡店',
    description: '暖黄蓝灰 · 文艺小清新 · 适合咖啡/探店/生活方式',
    pageBg: '#f6f2ea',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SERIF,
      color: '#3f3f3f',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#7fa6cf',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #f8e1ab',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#5a7ba6',
      'margin': '24px 0 14px',
      'padding': '9px 16px',
      'background': '#f5f9fc',
      'border-left': '5px solid #7fa6cf',
      'border-radius': '8px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#8aa6c4' },
    p: { 'margin': '14px 0', color: '#3f3f3f', 'line-height': '1.95' },
    strong: { color: '#7fa6cf', 'font-weight': '700' },
    em: { color: '#c49a5a', 'font-style': 'italic' },
    a: { color: '#7fa6cf', 'text-decoration': 'none', 'border-bottom': '1px solid #cfe0f0' },
    blockquote: {
      background: '#fbf3e0',
      'border-left': '4px solid #e8c98a',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b5a4a',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #f8e1ab', margin: '24px 0' },
    mark: { background: '#f8e1ab', color: '#5a3d00' },
  }),
  // 立秋：嫩绿 + 鹅黄 + 浅鹅黄底 · 节气文艺（复刻 135「立秋一键排版」）
  theme({
    id: 'solar-autumn',
    name: '立秋',
    description: '嫩绿鹅黄 · 浅鹅黄底 · 节气文艺，适合立秋/节气/散文',
    pageBg: '#f6f4e8',
    container: {
      background: '#fffdf6',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#4a453a',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#a6bb30',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #ffeb9a',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#5c6b2e',
      'margin': '24px 0 14px',
      'padding': '9px 16px',
      'background': '#f7fbc4',
      'border-left': '5px solid #e0e25e',
      'border-bottom': '2px solid #ffeb9a',
      'border-radius': '8px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#8a9a3a' },
    p: { 'margin': '14px 0', color: '#4a453a', 'line-height': '1.95' },
    strong: { color: '#a6bb30', 'font-weight': '700' },
    em: { color: '#c49a3a', 'font-style': 'italic' },
    a: { color: '#a6bb30', 'text-decoration': 'none', 'border-bottom': '1px solid #ffeb9a' },
    blockquote: {
      background: '#fbfbe9',
      'border-left': '4px solid #e0e25e',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#6b6548',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #e0e25e', margin: '24px 0' },
    mark: { background: '#ffeb9a', color: '#5a3d00' },
  }),
  // 系列报道：深蓝 + 浅蓝 + 暖黄点缀 · 政务新闻风（复刻 135「系列报道一键排版」）
  theme({
    id: 'reportblue',
    name: '报道蓝',
    description: '深蓝浅蓝 · 暖黄点缀 · 政务新闻，适合系列报道/专题/媒体',
    pageBg: '#eef4fb',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#333333',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#0867a6',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #ffc149',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#ffffff',
      'margin': '24px 0 14px',
      'padding': '9px 20px',
      'background': '#0867a6',
      'border-radius': '20px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#296cd4' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.95' },
    strong: { color: '#0867a6', 'font-weight': '700' },
    em: { color: '#c79a3a', 'font-style': 'italic' },
    a: { color: '#0867a6', 'text-decoration': 'none', 'border-bottom': '1px solid #d4e5ff' },
    blockquote: {
      background: '#f4f8ff',
      'border-left': '4px solid #0867a6',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#3a5a78',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #d4e5ff', margin: '24px 0' },
    mark: { background: '#ffc149', color: '#5a3d00' },
  }),
  // 读书日：深绿浅绿 · 暖黄点缀 · 读书活动风（复刻 135「读书日活动一键排版」）
  theme({
    id: 'readinggreen',
    name: '读书绿',
    description: '深绿浅绿 · 暖黄点缀 · 读书活动，适合读书日/阅读推广/文化',
    pageBg: '#eef5ec',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#333333',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#55963e',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #facc58',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#ffffff',
      'margin': '24px 0 14px',
      'padding': '9px 16px',
      'background': '#55963e',
      'border-radius': '7px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#5fa55a' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.95' },
    strong: { color: '#55963e', 'font-weight': '700' },
    em: { color: '#c79a3a', 'font-style': 'italic' },
    a: { color: '#55963e', 'text-decoration': 'none', 'border-bottom': '1px solid #b7d8a8' },
    blockquote: {
      background: '#f3f9f0',
      'border-left': '4px solid #55963e',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#4a6b45',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #b7d8a8', margin: '24px 0' },
    mark: { background: '#facc58', color: '#5a3d00' },
  }),
  // 年终好价节：暖红 + 暖黄 · 电商促销风（复刻 135「年终好价节一键排版」）
  theme({
    id: 'promored',
    name: '好价节红',
    description: '暖红暖黄 · 促销狂欢，适合电商大促/年货节/购物节',
    pageBg: '#fff6f3',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#333333',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#f95f61',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #ffc95f',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#ffffff',
      'margin': '24px 0 14px',
      'padding': '9px 16px',
      'background': '#f95f61',
      'border-radius': '7px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#f95f61' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.95' },
    strong: { color: '#f95f61', 'font-weight': '700' },
    em: { color: '#c79a3a', 'font-style': 'italic' },
    a: { color: '#f95f61', 'text-decoration': 'none', 'border-bottom': '1px solid #ffd9a0' },
    blockquote: {
      background: '#fff8de',
      'border-left': '4px solid #f95f61',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#7a4a3a',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #ffd9a0', margin: '24px 0' },
    mark: { background: '#ffe377', color: '#5a3d00' },
  }),
  // 萌宠粉：粉红浅底 · 胶囊标题 · 养宠课堂风（复刻 135「养宠课堂一键排版」）
  theme({
    id: 'petpink',
    name: '萌宠粉',
    description: '粉红浅底 · 胶囊标题 · 萌宠养宠，适合宠物/萌宠/生活/母婴',
    pageBg: '#fdeef0',
    container: {
      background: '#fffafa',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#5a3a3f',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#f26077',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #ffd1d9',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#f26077',
      'text-align': 'center',
      'margin': '24px auto 14px',
      'background': '#ffd1d9',
      'border-radius': '20px',
      'padding': '7px 25px',
      'display': 'table',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#eb6e6e' },
    p: { 'margin': '14px 0', color: '#5a3a3f', 'line-height': '1.95' },
    strong: { color: '#f26077', 'font-weight': '700' },
    em: { color: '#c79a3a', 'font-style': 'italic' },
    a: { color: '#f26077', 'text-decoration': 'none', 'border-bottom': '1px solid #ffd1d9' },
    blockquote: {
      background: '#fff0f3',
      'border-left': '4px solid #f26077',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#8a5a60',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #ffd1d9', margin: '24px 0' },
    mark: { background: '#ffd1d9', color: '#c23a52' },
  }),
  // 谷雨时节：春意嫩绿 · 浅绿底胶囊标题（复刻 135「谷雨时节一键排版」）
  theme({
    id: 'gutengreen',
    name: '谷雨绿',
    description: '春意嫩绿 · 浅绿底胶囊标题 · 节气时令，适合节气/散文/随笔/生活',
    pageBg: '#eef6e6',
    container: {
      background: '#f9fef4',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#3f4a35',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#6da534',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #cae6b2',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#6da534',
      'text-align': 'center',
      'margin': '24px auto 14px',
      'background': '#e7f7d6',
      'border-radius': '20px',
      'padding': '7px 25px',
      'display': 'table',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#8ab85c' },
    p: { 'margin': '14px 0', color: '#3f4a35', 'line-height': '1.95' },
    strong: { color: '#5a9233', 'font-weight': '700' },
    em: { color: '#8ab85c', 'font-style': 'italic' },
    a: { color: '#6da534', 'text-decoration': 'none', 'border-bottom': '1px solid #cae6b2' },
    blockquote: {
      background: '#f4fbed',
      'border-left': '4px solid #6da534',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#5c6b48',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #cae6b2', margin: '24px 0' },
    mark: { background: '#e7f7d6', color: '#4f7a2c' },
  }),
  // 书单蓝 · 书单推荐：清新天蓝 + 彩色圆点点缀（复刻 135「书单推荐一键排版」）
  theme({
    id: 'booklist',
    name: '书单蓝',
    description: '清新天蓝 · 浅蓝底胶囊标题 · 书单推荐，适合书单/阅读/文学/图书馆',
    pageBg: '#eef7fc',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#3f3f3f',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#47bdeb',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #c7ebfa',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#2b8fc4',
      'text-align': 'center',
      'margin': '24px auto 14px',
      'background': '#ebf9fe',
      'border-radius': '20px',
      'padding': '7px 25px',
      'display': 'table',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#61c9f3' },
    p: { 'margin': '14px 0', color: '#3f3f3f', 'line-height': '1.95' },
    strong: { color: '#2b8fc4', 'font-weight': '700' },
    em: { color: '#a6c954', 'font-style': 'italic' },
    a: { color: '#47bdeb', 'text-decoration': 'none', 'border-bottom': '1px solid #c7ebfa' },
    blockquote: {
      background: '#ebf9fe',
      'border-left': '4px solid #47bdeb',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#3a6b85',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #c7ebfa', margin: '24px 0' },
    mark: { background: '#ebf9fe', color: '#2b8fc4' },
  }),
  theme({
    id: 'annivgold',
    name: '校庆金蓝',
    description: '金蓝双色喜庆 · 蓝底白字胶囊标题 · 周年校庆，适合校庆/庆典/活动/纪念日',
    pageBg: '#f7fcff',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#3a3a3a',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#2e7bb5',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #ffca42',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#ffffff',
      'text-align': 'center',
      'margin': '24px auto 14px',
      background: '#6ec1f5',
      'border-radius': '20px',
      'padding': '7px 25px',
      'display': 'table',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#e0a800' },
    p: { 'margin': '14px 0', color: '#3a3a3a', 'line-height': '1.95' },
    strong: { color: '#2e7bb5', 'font-weight': '700' },
    em: { color: '#e0a800', 'font-style': 'italic' },
    a: { color: '#6ec1f5', 'text-decoration': 'none', 'border-bottom': '1px solid #c7ebfa' },
    blockquote: {
      background: '#f7fcff',
      'border-left': '4px solid #ffca42',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#5a5a3a',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #ffca42', margin: '24px 0' },
    mark: { background: '#fff4d6', color: '#b8860b' },
  }),
  theme({
    id: 'dadblue',
    name: '父爱深蓝',
    description: '父爱深蓝 · 浅蓝底深蓝字标题块 · 父亲节，适合亲情/父亲节/感恩/家庭',
    pageBg: '#eef6fc',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#333333',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '23px',
      'font-weight': '700',
      color: '#055698',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #bae9fb',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '18px',
      'font-weight': '700',
      color: '#055698',
      'text-align': 'center',
      'margin': '24px auto 14px',
      background: '#f2f9fc',
      'border-radius': '20px',
      'padding': '7px 25px',
      'display': 'table',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#1a7fc4' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.95' },
    strong: { color: '#055698', 'font-weight': '700' },
    em: { color: '#1a7fc4', 'font-style': 'italic' },
    a: { color: '#055698', 'text-decoration': 'none', 'border-bottom': '1px solid #bae9fb' },
    blockquote: {
      background: '#f2f9fc',
      'border-left': '4px solid #055698',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#2a4a63',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #bae9fb', margin: '24px 0' },
    mark: { background: '#f2f9fc', color: '#055698' },
  }),
  // 智慧教育：科技蓝 · 浅蓝底 · 适合教育/智慧课堂/校园/培训
  theme({
    id: 'smartedu',
    name: '智慧教育',
    description: '科技蓝 · 浅蓝底 · 适合教育/智慧课堂/校园/培训',
    pageBg: '#eef6ff',
    container: {
      background: '#ffffff',
      padding: '28px 22px',
      'font-family': SANS,
      color: '#333333',
      'font-size': '16px',
      'line-height': '1.95',
      'letter-spacing': '0.3px',
    },
    h1: {
      'font-size': '24px',
      'font-weight': '700',
      color: '#1e6ee6',
      'text-align': 'center',
      'margin': '30px 0 16px',
      'letter-spacing': '2px',
      'border-bottom': '3px solid #b8d7ff',
      'padding-bottom': '12px',
    },
    h2: {
      'font-size': '19px',
      'font-weight': '700',
      color: '#1e6ee6',
      'margin': '24px 0 14px',
      'border-left': '5px solid #1e6ee6',
      'padding-left': '12px',
    },
    h3: { 'font-size': '16px', 'font-weight': '600', color: '#1e6ee6' },
    p: { 'margin': '14px 0', color: '#333333', 'line-height': '1.95' },
    strong: { color: '#1e6ee6', 'font-weight': '700' },
    em: { color: '#4a8af0', 'font-style': 'italic' },
    a: { color: '#1e6ee6', 'text-decoration': 'none', 'border-bottom': '1px solid #b8d7ff' },
    blockquote: {
      background: '#f0f7ff',
      'border-left': '4px solid #1e6ee6',
      padding: '12px 16px',
      margin: '16px 0',
      color: '#3a5a85',
      'border-radius': '0 10px 10px 0',
    },
    hr: { border: 'none', 'border-top': '1px dashed #b8d7ff', margin: '24px 0' },
    mark: { background: '#e0efff', color: '#0546a8' },
  }),
]
